[plugins]
kotlin-jvm = "org.jetbrains.kotlin.jvm:2.2.21"
kotlinx-serialization = "org.jetbrains.kotlin.plugin.serialization:2.2.21"
detekt = "io.gitlab.arturbosch.detekt:1.23.8"
ktlint = "org.jlleitschuh.gradle.ktlint:14.0.1"
shadow = "com.gradleup.shadow:9.2.2"
test-logger = "com.adarshr.test-logger:4.0.0"

[libraries]

# Application
ajalt-clikt = "com.github.ajalt.clikt:clikt:5.1.0"
ajalt-mordant = "com.github.ajalt.mordant:mordant:3.0.2"
arrow-core = "io.arrow-kt:arrow-core:2.2.1.1"

android-tools-sdklib = "com.android.tools:sdklib:31.13.2"
android-tools-apkanalyzer = "com.android.tools.apkparser:apkanalyzer:31.13.2"
android-tools-binaryresources = "com.android.tools.apkparser:binary-resources:31.13.2"
android-tools-repository = "com.android.tools:repository:31.13.2"
android-tools-sdkcommon = "com.android.tools:sdk-common:31.13.2"
android-tools-common = "com.android.tools:common:31.13.2"
android-tools-bundletool = "com.android.tools.build:bundletool:1.18.3"

kotlinx-serialization-core = "org.jetbrains.kotlinx:kotlinx-serialization-core:1.10.0"
kotlinx-serialization-jvm = "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.10.0"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"
peanutz-tomlkt = "net.peanuuutz.tomlkt:tomlkt:0.5.0"

# Testing
junit = "junit:junit:4.13.2"
google-guava = "com.google.guava:guava:33.5.0-jre"
google-truth = "com.google.truth:truth:1.4.5"
